services:
  - type: web
    name: sp-i-e
    runtime: static
    buildCommand: yarn; yarn build
    staticPublishPath: out
    pullRequestPreviewsEnabled: true # optional
    envVars:
      - key: NODE_ENV
        value: production
